[2024-12-09 16:37:48 +0000] [16014] [INFO] Starting gunicorn 23.0.0
[2024-12-09 16:37:48 +0000] [16014] [INFO] Listening at: http://0.0.0.0:8000 (16014)
[2024-12-09 16:37:48 +0000] [16014] [INFO] Using worker: sync
[2024-12-09 16:37:48 +0000] [16043] [INFO] Booting worker with pid: 16043
[2024-12-09 16:37:48 +0000] [16043] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grizzly_server'
[2024-12-09 16:37:48 +0000] [16043] [INFO] Worker exiting (pid: 16043)
[2024-12-09 16:37:48 +0000] [16014] [ERROR] Worker (pid:16043) exited with code 3
[2024-12-09 16:37:48 +0000] [16014] [ERROR] Shutting down: Master
[2024-12-09 16:37:48 +0000] [16014] [ERROR] Reason: Worker failed to boot.
[2024-12-09 16:38:28 +0000] [18916] [INFO] Starting gunicorn 23.0.0
[2024-12-09 16:38:28 +0000] [18916] [INFO] Listening at: http://0.0.0.0:8000 (18916)
[2024-12-09 16:38:28 +0000] [18916] [INFO] Using worker: sync
[2024-12-09 16:38:28 +0000] [18941] [INFO] Booting worker with pid: 18941
[2024-12-09 16:38:28 +0000] [18941] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grizzly_server'
[2024-12-09 16:38:28 +0000] [18941] [INFO] Worker exiting (pid: 18941)
[2024-12-09 16:38:28 +0000] [18942] [INFO] Booting worker with pid: 18942
[2024-12-09 16:38:28 +0000] [18942] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/Documents/domains/grizzly-server/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grizzly/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grizzly_server'
[2024-12-09 16:38:28 +0000] [18942] [INFO] Worker exiting (pid: 18942)
[2024-12-09 16:38:28 +0000] [18916] [ERROR] Worker (pid:18941) exited with code 3
[2024-12-09 16:38:28 +0000] [18916] [ERROR] Worker (pid:18942) was sent SIGTERM!
[2024-12-09 16:38:28 +0000] [18916] [ERROR] Shutting down: Master
[2024-12-09 16:38:28 +0000] [18916] [ERROR] Reason: Worker failed to boot.
